# Generated by Django 3.1.3 on 2020-11-14 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import session_manager.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64)),
                ('token_type', models.CharField(choices=[('reset', 'reset'), ('login', 'login')], max_length=20, unique=True)),
                ('expiration', models.DateTimeField(blank=True, default=session_manager.utils.twentyfourhoursfromnow)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
