# Generated by Django 3.1.3 on 2020-12-08 12:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teambeat.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('admins', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambeat.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, teambeat.models.DjangoUserMixin),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teambeat.organization')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamlead_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('organization_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambeat.organizationuser')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambeat.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime.today)),
                ('status', models.CharField(choices=[('green', 'green'), ('red', 'red'), ('yellow', 'yellow')], max_length=10)),
                ('additional_info_for_team', models.TextField(blank=True, null=True)),
                ('additional_info_for_lead', models.TextField(blank=True, null=True)),
                ('teammember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambeat.teammember')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambeat.organizationuser')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambeat.team')),
            ],
            bases=(models.Model, teambeat.models.DjangoUserMixin),
        ),
    ]
