# Generated by Django 3.1.3 on 2020-12-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambeat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamlead',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='team_lead',
            field=models.ManyToManyField(to='teambeat.TeamLead'),
        ),
    ]
