# Generated by Django 3.1.3 on 2020-12-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambeat', '0003_organizationuser_is_organization_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
