# Generated by Django 3.1.3 on 2020-12-09 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teambeat', '0005_organizationinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvitation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
