# Generated by Django 3.1.3 on 2020-12-07 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teambeat', '0005_auto_20201207_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_lead',
        ),
        migrations.DeleteModel(
            name='TeamLead',
        ),
    ]
