# Generated by Django 3.1.3 on 2020-12-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambeat', '0007_team_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
