# Generated by Django 3.1.3 on 2020-12-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambeat', '0008_teammember_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammemberstatus',
            old_name='additional_info',
            new_name='additional_info_for_lead',
        ),
        migrations.AddField(
            model_name='teammemberstatus',
            name='additional_info_for_team',
            field=models.TextField(blank=True, null=True),
        ),
    ]
